# SPDX-License-Identifier: GPL-2.0+
# board/genexis/xg6846b/Makefile

obj-y += xg6846b.o

# Pull in the XRDP data-path init table from the SDK
# (data_path_6846.c + access_logging.c must be in the build)
obj-y += data_path_6846.o
obj-y += access_logging.o
obj-y += rdp_drv_sbpm.o
